/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salonproject;
import java.sql.*;
import oracle.jdbc.*;
import oracle.sql.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class addService extends javax.swing.JFrame {

    /**
     * Creates new form addService
     */
    public addService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        duration = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        materials = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("add  Service");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 320, 45));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Service ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, 34));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 259, 34));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 259, 34));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Service Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 34));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Service Duration");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 34));
        jPanel1.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 259, 34));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 259, 34));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Service Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 140, 34));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Service Materials");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 140, 34));
        jPanel1.add(materials, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 259, 34));

        back.setBackground(new java.awt.Color(0, 0, 102));
        back.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 102, 204));
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 120, -1));

        delete.setBackground(new java.awt.Color(0, 0, 102));
        delete.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 102, 204));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 120, -1));

        add.setBackground(new java.awt.Color(0, 0, 102));
        add.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 102, 204));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 130, -1));

        search.setBackground(new java.awt.Color(0, 0, 102));
        search.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 102, 204));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/864f04120615ed23e9cbca4c2d9d712e.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        adminmenu ob = new adminmenu();
        ob.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            DriverManager.registerDriver(new oracle .jdbc.driver.OracleDriver());
            String url,user,password;
            url="jdbc:oracle:thin:@localhost:1521:xe";
            user="c##lena";
            password="654321";
            Connection con=DriverManager.getConnection(url, user, password);
            con.setAutoCommit(false);
            Statement stmt=con.createStatement();

            String usnu=this.id.getText();
            //String cid=this.cid.getText();


            if(usnu.isEmpty()){

                JOptionPane.showMessageDialog(null, "please fill all data!");
            }
            if(!(usnu.isEmpty())){
                String sqlstr="delete from SALONSERVICE where SERVICEID='"+usnu+"'";
                stmt.execute(sqlstr);
                con.commit();
                con.close();
                JOptionPane.showMessageDialog(null, "delete successfully ^-^");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try {
            DriverManager.registerDriver(new oracle .jdbc.driver.OracleDriver());
            String url,user,password;
            url="jdbc:oracle:thin:@localhost:1521:xe";
            user="c##lena";
            password="654321";
            Connection con=DriverManager.getConnection(url, user, password);
          con.setAutoCommit(false);
            Statement stmt=con.createStatement();
          
           
            String id=this.id.getText();
            String name=this.name.getText();
           
            String duration=this.duration.getText();
            String price=this.price.getText();
            
            String materials=this.materials.getText();
          
           
            if( id.isEmpty()|| name.isEmpty() || duration.isEmpty() || price.isEmpty() ||materials.isEmpty() ){
 
                    JOptionPane.showMessageDialog(null, "please fill all data!");
               }
            if(!( id.isEmpty()|| name.isEmpty() || duration.isEmpty() || price.isEmpty() ||materials.isEmpty() )){
            String sqlstr="insert into SALONSERVICE values ('"+id+"','"+name+" ','"+duration+"' ,'"+price+"','"+materials+"')";
            stmt.execute(sqlstr);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "add successfully ^-^");
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            //Logger.getLogger(addcustomers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_addActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    try {
            DriverManager.registerDriver(new oracle .jdbc.driver.OracleDriver());
            String url,user,password;
            url="jdbc:oracle:thin:@localhost:1521:xe";
            user="c##lena";
            password="654321";
            Connection con=DriverManager.getConnection(url, user, password);
            con.setAutoCommit(false);
            Statement stmt=con.createStatement();

            String usnu=this.id.getText();
            //String cuid=this.cid.getText();
            // String sq=this.jTextsq.getText();

            if(usnu.isEmpty()){

                JOptionPane.showMessageDialog(null, "please fill Username!");
            }
            if(!(usnu.isEmpty())){
                String sqlstr="select * from SALONSERVICE where SERVICEID= '"+usnu+"'";
                ResultSet rs=stmt.executeQuery(sqlstr);
                while(rs.next()){
                    id.setText(rs.getString("SERVICEID"));
                    name.setText(rs.getString("SERVICENAME"));
                    duration.setText(rs.getString("SERVICEDURATION"));
                    price.setText(rs.getString("SERVICEPRICE"));
                    materials.setText(rs.getString("SERVICEMATERIALS"));

            

                }

                con.commit();
                con.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            //Logger.getLogger(addcustomers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JTextField duration;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField materials;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
